# Generated by Django 5.2.8 on 2025-11-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_country'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdsession',
            name='bid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='demo_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='last_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='network',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], default='mtn', max_length=20),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='selected_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussd_sessions', to='auctions.item'),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='stage',
            field=models.CharField(choices=[('main_menu', 'Main Menu'), ('item_selection', 'Item Selection'), ('item_details', 'Item Details'), ('bid_entry', 'Bid Entry'), ('pin_entry', 'PIN Entry'), ('confirmation', 'Confirmation'), ('completed', 'Completed')], default='main_menu', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('web', 'Web')], max_length=20),
        ),
    ]
