# Generated by Django 5.2.8 on 2025-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ussdsession_bid_amount_ussdsession_demo_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='platform_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
