# Generated by Django 5.2.8 on 2025-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_platform_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='stage',
            field=models.CharField(choices=[('main_menu', 'Main Menu'), ('item_selection', 'Item Selection'), ('item_details', 'Item Details'), ('bid_entry', 'Bid Entry'), ('pin_entry', 'PIN Entry'), ('confirmation', 'Confirmation'), ('completed', 'Completed'), ('listing_title', 'Listing Title'), ('listing_description', 'Listing Description'), ('listing_category', 'Listing Category'), ('listing_price', 'Listing Price'), ('listing_duration', 'Listing Duration'), ('listing_review', 'Listing Review'), ('listing_confirm', 'Listing Confirm')], default='main_menu', max_length=20),
        ),
    ]
