# Generated by Django 5.2.8 on 2025-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
