# Generated by Django 5.2.8 on 2025-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_hide_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('stanbic', 'Stanbic Bank'), ('dfcu', 'DFCU Bank'), ('centenary', 'Centenary Bank'), ('equity', 'Equity Bank'), ('absa', 'Absa Bank'), ('standard_chartered', 'Standard Chartered'), ('barclays', 'Barclays Bank'), ('other', 'Other')], max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual Seller'), ('small_business', 'Small Business'), ('company', 'Registered Company'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer')], max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='product_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_status',
            field=models.CharField(choices=[('none', 'Not Applied'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
