# Generated by Django 5.2.8 on 2025-11-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='national_id_back',
            field=models.ImageField(blank=True, null=True, upload_to='id_verification/back/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id_front',
            field=models.ImageField(blank=True, null=True, upload_to='id_verification/front/'),
        ),
    ]
