# Generated by Django 5.2.8 on 2025-11-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_loginattempt_twofactorauth_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
