# Generated by Django 5.2.8 on 2025-11-09 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_totp_secret_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bypass_account_age_check',
            field=models.BooleanField(default=False, help_text='Allow high-value bids regardless of account age'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_all_restrictions',
            field=models.BooleanField(default=False, help_text='Bypass ALL security checks (use with extreme caution)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_fraud_detection',
            field=models.BooleanField(default=False, help_text="Fraud alerts logged but won't block bids"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bypass_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_notes',
            field=models.TextField(blank=True, help_text='Admin notes explaining why bypass was granted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bypass_rapid_bidding_check',
            field=models.BooleanField(default=False, help_text='Exempt from rapid bidding detection and CAPTCHA challenges'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_trusted_user',
            field=models.BooleanField(default=False, help_text='Mark user as trusted (shows in admin dashboard)'),
        ),
    ]
