# Generated by Django 5.2.8 on 2025-11-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_min_increment_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
    ]
