# Generated by Django 5.2.8 on 2025-11-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('private', 'Private'), ('off_sale', 'Off Sale')], default='active', max_length=10),
        ),
    ]
