# Generated by Django 5.2.8 on 2025-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_via',
            field=models.CharField(choices=[('web', 'Web'), ('ussd', 'USSD')], default='web', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='requires_media_followup',
            field=models.BooleanField(default=False),
        ),
    ]
