# Generated by Django 5.2.8 on 2025-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_item_free_shipping_item_pickup_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippinglocation',
            options={'ordering': ['country', 'city', 'area']},
        ),
        migrations.AlterUniqueTogether(
            name='shippinglocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shippinglocation',
            name='country',
            field=models.CharField(default='UG', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='shippinglocation',
            unique_together={('country', 'city', 'area')},
        ),
    ]
