# Generated by Django 5.2.8 on 2025-11-09 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_shippinglocation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_type', models.CharField(choices=[('soft_challenge', 'Soft Challenge Required'), ('hard_cooldown', 'Hard Cooldown'), ('captcha_failed', 'CAPTCHA Failed'), ('suspended', 'Suspended')], default='hard_cooldown', max_length=20)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('captcha_required', models.BooleanField(default=False)),
                ('captcha_passed', models.BooleanField(default=False)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_cooldowns', to='auctions.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_cooldowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'item', 'is_active', 'expires_at'], name='auctions_bi_user_id_7a4d3f_idx'), models.Index(fields=['expires_at', 'is_active'], name='auctions_bi_expires_f4eeb7_idx')],
            },
        ),
    ]
