"""
Django settings for auction_system project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import pymysql
from decouple import config, Csv

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-e8gxtg#&agik-f53_)2m5pm*(nik#u#y9xdqljwcdph))r8vx+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Security: In production, set specific allowed hosts
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

CSRF_TRUSTED_ORIGINS = []
if os.environ.get('REPLIT_DOMAINS'):
    replit_domain = os.environ.get('REPLIT_DOMAINS')
    CSRF_TRUSTED_ORIGINS.append(f'https://{replit_domain}')
    
if os.environ.get('REPL_SLUG') and os.environ.get('REPL_OWNER'):
    CSRF_TRUSTED_ORIGINS.extend([
        f'https://{os.environ.get("REPL_SLUG")}.{os.environ.get("REPL_OWNER")}.repl.co',
        f'https://{os.environ.get("REPL_SLUG")}-{os.environ.get("REPL_OWNER")}.replit.app',
    ])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'captcha',
    'auctions',
    'users',
    'payments',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.UpdateLastSeenMiddleware',
    'users.rate_limiting.RateLimitMiddleware',
]

ROOT_URLCONF = 'auction_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'auction_system.wsgi.application'
ASGI_APPLICATION = 'auction_system.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('USE_MYSQL') == 'true':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'auction_db'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

PASSWORD_HASHERS = [
    'auction_system.hashers.PBKDF2PasswordHasher600k',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_ATTEMPT_LIMIT = 5
LOGIN_LOCKOUT_DURATION = 15


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.environ.get("REDIS_HOST", "127.0.0.1"), 6379)],
        },
    },
}

# Cache (for rate limiting and general caching)
# Gracefully falls back to in-memory cache if Redis is unavailable

def test_redis_connection():
    """Test if Redis is available and accessible"""
    try:
        import redis
        redis_host = os.environ.get('REDIS_HOST', '127.0.0.1')
        r = redis.Redis(host=redis_host, port=6379, db=1, socket_connect_timeout=2)
        r.ping()
        return True
    except Exception:
        return False

# Check if Redis should be used and is available
REDIS_AVAILABLE = config('REDIS_AVAILABLE', default='auto', cast=str)

if REDIS_AVAILABLE == 'auto':
    # Auto-detect Redis availability
    USE_REDIS = test_redis_connection()
elif REDIS_AVAILABLE.lower() in ('true', '1', 'yes'):
    USE_REDIS = True
else:
    USE_REDIS = False

if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"redis://{os.environ.get('REDIS_HOST', '127.0.0.1')}:6379/1",
            "OPTIONS": {
                "db": "1",  # Use database 1 for cache (database 0 for Channels)
            },
            "TIMEOUT": 300,  # Default timeout
        }
    }
    print("✓ Using Redis cache")
else:
    # Fall back to in-memory cache for development without Redis
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "auction-cache",
        }
    }
    print("⚠ Redis unavailable, using LocMemCache fallback")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Production Security Settings
if not DEBUG:
    # HTTPS/SSL
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Proxy headers for deployment behind reverse proxy
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Rate Limiting (will be implemented via middleware)
RATELIMIT_ENABLE = config('RATELIMIT_ENABLE', default=True, cast=bool)
RATELIMIT_USE_CACHE = 'default'

# OpenAI Configuration
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

# Payment Gateway Configuration
FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY', default='')
FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY', default='')
FLUTTERWAVE_ENCRYPTION_KEY = config('FLUTTERWAVE_ENCRYPTION_KEY', default='')

STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')

PAYPAL_CLIENT_ID = config('PAYPAL_CLIENT_ID', default='')
PAYPAL_CLIENT_SECRET = config('PAYPAL_CLIENT_SECRET', default='')
PAYPAL_MODE = config('PAYPAL_MODE', default='sandbox')

# Africa's Talking Configuration
AFRICASTALKING_USERNAME = config('AFRICASTALKING_USERNAME', default='sandbox')
AFRICASTALKING_API_KEY = config('AFRICASTALKING_API_KEY', default='')
AFRICASTALKING_SHORTCODE = config('AFRICASTALKING_SHORTCODE', default='*384*12345#')

# Platform Tax Rate
TAX_RATE = 0.05  # 5% platform fee

# Fraud Prevention: New Account Bid Limits
# Minimum account age (in days) required to place bids above the high-value threshold
MIN_ACCOUNT_AGE_FOR_HIGH_BIDS = config('MIN_ACCOUNT_AGE_FOR_HIGH_BIDS', default=7, cast=int)
# Bid amount threshold (in UGX) that triggers account age check
HIGH_VALUE_BID_THRESHOLD = config('HIGH_VALUE_BID_THRESHOLD', default=1000000, cast=int)

# Fraud Detection Thresholds
RAPID_BIDDING_WINDOW_MINUTES = config('RAPID_BIDDING_WINDOW_MINUTES', default=5, cast=int)
RAPID_BIDDING_THRESHOLD = config('RAPID_BIDDING_THRESHOLD', default=10, cast=int)

BID_SNIPING_WINDOW_SECONDS = config('BID_SNIPING_WINDOW_SECONDS', default=60, cast=int)
BID_SNIPING_HISTORY_DAYS = config('BID_SNIPING_HISTORY_DAYS', default=7, cast=int)
BID_SNIPING_THRESHOLD = config('BID_SNIPING_THRESHOLD', default=5, cast=int)

UNUSUAL_BID_MULTIPLIER = config('UNUSUAL_BID_MULTIPLIER', default=3, cast=float)

BID_PATTERN_MIN_HISTORY = config('BID_PATTERN_MIN_HISTORY', default=10, cast=int)
BID_PATTERN_DEVIATION_MULTIPLIER = config('BID_PATTERN_DEVIATION_MULTIPLIER', default=5, cast=float)

SHILL_MIN_TOTAL_BIDS = config('SHILL_MIN_TOTAL_BIDS', default=10, cast=int)
SHILL_MIN_SELLER_BIDS = config('SHILL_MIN_SELLER_BIDS', default=5, cast=int)
SHILL_AFFINITY_THRESHOLD = config('SHILL_AFFINITY_THRESHOLD', default=0.4, cast=float)

LOW_WIN_RATIO_MIN_BIDS = config('LOW_WIN_RATIO_MIN_BIDS', default=15, cast=int)
LOW_WIN_RATIO_THRESHOLD = config('LOW_WIN_RATIO_THRESHOLD', default=0.05, cast=float)

SELLER_AFFINITY_MIN_AUCTIONS = config('SELLER_AFFINITY_MIN_AUCTIONS', default=5, cast=int)
SELLER_AFFINITY_PARTICIPATION_THRESHOLD = config('SELLER_AFFINITY_PARTICIPATION_THRESHOLD', default=0.5, cast=float)

TIMING_PATTERN_EARLY_THRESHOLD = config('TIMING_PATTERN_EARLY_THRESHOLD', default=0.25, cast=float)
TIMING_PATTERN_LATE_THRESHOLD = config('TIMING_PATTERN_LATE_THRESHOLD', default=0.8, cast=float)
TIMING_PATTERN_MIN_EARLY_BIDS = config('TIMING_PATTERN_MIN_EARLY_BIDS', default=10, cast=int)
TIMING_PATTERN_LATE_RATIO_THRESHOLD = config('TIMING_PATTERN_LATE_RATIO_THRESHOLD', default=0.1, cast=float)

COLLUSIVE_COMMON_ITEMS_THRESHOLD = config('COLLUSIVE_COMMON_ITEMS_THRESHOLD', default=5, cast=int)
COLLUSIVE_SUSPICIOUS_PAIRS_THRESHOLD = config('COLLUSIVE_SUSPICIOUS_PAIRS_THRESHOLD', default=2, cast=int)

FAILED_PAYMENT_WINDOW_DAYS = config('FAILED_PAYMENT_WINDOW_DAYS', default=30, cast=int)
FAILED_PAYMENT_THRESHOLD = config('FAILED_PAYMENT_THRESHOLD', default=3, cast=int)

HIGH_VALUE_PAYMENT_THRESHOLD = config('HIGH_VALUE_PAYMENT_THRESHOLD', default=10000000, cast=int)

MULTIPLE_PAYMENT_METHODS_WINDOW_HOURS = config('MULTIPLE_PAYMENT_METHODS_WINDOW_HOURS', default=24, cast=int)
MULTIPLE_PAYMENT_METHODS_THRESHOLD = config('MULTIPLE_PAYMENT_METHODS_THRESHOLD', default=3, cast=int)

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@auctionhub.com')

# Advanced Rapid Bidding Detection Settings
# Per-auction soft challenge thresholds (triggers CAPTCHA)
RAPID_BID_SOFT_WINDOW_2MIN = config('RAPID_BID_SOFT_WINDOW_2MIN', default=2, cast=int)
RAPID_BID_SOFT_THRESHOLD_2MIN = config('RAPID_BID_SOFT_THRESHOLD_2MIN', default=5, cast=int)
RAPID_BID_SOFT_WINDOW_5MIN = config('RAPID_BID_SOFT_WINDOW_5MIN', default=5, cast=int)
RAPID_BID_SOFT_THRESHOLD_5MIN = config('RAPID_BID_SOFT_THRESHOLD_5MIN', default=8, cast=int)

# Per-auction hard action thresholds (temporary cooldown)
RAPID_BID_HARD_WINDOW_5MIN = config('RAPID_BID_HARD_WINDOW_5MIN', default=5, cast=int)
RAPID_BID_HARD_THRESHOLD_5MIN = config('RAPID_BID_HARD_THRESHOLD_5MIN', default=12, cast=int)
RAPID_BID_HARD_WINDOW_20SEC = config('RAPID_BID_HARD_WINDOW_20SEC', default=20, cast=int)
RAPID_BID_HARD_THRESHOLD_20SEC = config('RAPID_BID_HARD_THRESHOLD_20SEC', default=3, cast=int)

# Cooldown duration for hard action (in seconds)
RAPID_BID_COOLDOWN_DURATION = config('RAPID_BID_COOLDOWN_DURATION', default=90, cast=int)

# Auction endgame window (last N minutes)
AUCTION_ENDGAME_WINDOW_MINUTES = config('AUCTION_ENDGAME_WINDOW_MINUTES', default=2, cast=int)
# Endgame multiplier (raise thresholds by this factor, e.g., 1.5 = 50% increase)
AUCTION_ENDGAME_MULTIPLIER = config('AUCTION_ENDGAME_MULTIPLIER', default=1.5, cast=float)

# Global cross-auction velocity (soft challenge)
GLOBAL_VELOCITY_SOFT_WINDOW_MINUTES = config('GLOBAL_VELOCITY_SOFT_WINDOW_MINUTES', default=10, cast=int)
GLOBAL_VELOCITY_SOFT_THRESHOLD_BIDS = config('GLOBAL_VELOCITY_SOFT_THRESHOLD_BIDS', default=20, cast=int)
GLOBAL_VELOCITY_SOFT_THRESHOLD_AUCTIONS = config('GLOBAL_VELOCITY_SOFT_THRESHOLD_AUCTIONS', default=3, cast=int)

# Global cross-auction velocity (hard action)
GLOBAL_VELOCITY_HARD_WINDOW_MINUTES = config('GLOBAL_VELOCITY_HARD_WINDOW_MINUTES', default=30, cast=int)
GLOBAL_VELOCITY_HARD_THRESHOLD_BIDS = config('GLOBAL_VELOCITY_HARD_THRESHOLD_BIDS', default=50, cast=int)
GLOBAL_VELOCITY_HARD_THRESHOLD_AUCTIONS = config('GLOBAL_VELOCITY_HARD_THRESHOLD_AUCTIONS', default=5, cast=int)

# Minimum increment sanity check
MIN_INCREMENT_WINDOW_SECONDS = config('MIN_INCREMENT_WINDOW_SECONDS', default=30, cast=int)
MIN_INCREMENT_THRESHOLD_BIDS = config('MIN_INCREMENT_THRESHOLD_BIDS', default=3, cast=int)

# Captcha settings
CAPTCHA_FONT_SIZE = 30
CAPTCHA_LETTER_ROTATION = (-35, 35)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.math_challenge'
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_arcs', 'captcha.helpers.noise_dots')
